version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - MINI_APP_URL=${MINI_APP_URL}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    healthcheck:
      test: ["CMD", "cat", "/app/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - web-app 